=begin

  @File Name                            :application_controller.rb

	@Company Name                         :Mindfire Solutions Pvt. Ltd.

	@Creator Name                         :Indranil Mukherjee 

	@Date Created                         :2012-06-04

  @Date Modified                        :2012-06-14

  @Last Modification Details            :Making it as mcms project standard

  @Purpose                              :This file is mother of all controllers in the system
                                         and responsible of doing the common operations for all
                                         controllers.

=end


class ApplicationController < ActionController::Base

  #this protects from outside forgery , i.e : form submissions from outside (remote side)
  protect_from_forgery

  #  The following snippet is responsible for rescuing from exception generated by CanCan gem
  #  for denying a particular module access with a notice to user and redirecting to root_url
  rescue_from CanCan::AccessDenied do |exception|

    flash[:error] = t(:access_denied,:default => "You are not authorized for doing this operation")
    redirect_to root_url
       
  end
  
end
